
#define INVALID_BISHOP_MOVE 7
#define NO_PIECE_AT_REQUESTED_MOVE 6
#define INVALID_ROOK_MOVE 5
#define PIECE_BLOCKED 4
#define PAWN_INVALID_MOVE 3
#define POSITION_REQUESTED_OUT_OF_RANGE 2
#define SPACE_OCCUPIED_BY_SAME_COLOUR 1
#define MOVE_VALID 0
