
#define CHECKMATE 14
#define UNABLE_TO_CLEAR_LIST 13
#define NO_PIECE_AT_REQUESTED_MOVE_CHECK 12
#define INCORRECT_COLOUR_MOVE 11
#define KNIGHT_INVALID_MOVE 10
#define INVALID_KING_MOVE 9
#define INVALID_QUEEN_MOVE 8
#define INVALID_BISHOP_MOVE 7
#define NO_PIECE_AT_REQUESTED_MOVE 6
#define INVALID_ROOK_MOVE 5
#define PIECE_BLOCKED 4
#define PAWN_INVALID_MOVE 3
#define POSITION_REQUESTED_OUT_OF_RANGE 2
#define SPACE_OCCUPIED_BY_SAME_COLOUR 1
#define MOVE_VALID 0
